// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiKeyGrok": string;
      "apiKeyOpenai": string;
      "apiKeyAnthropic": string;
      "apiKeyGemini": string;
      "apiKeyOllama": string;
      "model": string;
    };
  }
}
