/**
 * Context menu registration and handling
 */

import {
  extractPdfText,
  getAbstract,
  getTitle,
  getCitationKey,
} from "./pdfExtract";
import { generateSummary } from "./grokApi";
import {
  createSummaryNote,
  findExistingNote,
  deleteAutoGeneratedNotes,
} from "./noteCreator";
import { getApiKey, getModel } from "../utils/prefs";
import { getString } from "../utils/locale";
import { config } from "../../package.json";

/**
 * Register the context menu item using Zotero.MenuManager (Zotero 8+)
 */
export function registerMenu(): void {
  Zotero.MenuManager.registerMenu({
    menuID: `${config.addonRef}-generate-summary`,
    pluginID: config.addonID,
    target: "main/library/item",
    menus: [
      {
        menuType: "menuitem",
        icon: `chrome://${config.addonRef}/content/icons/favicon.png`,
        onShowing: (_event, context) => {
          context.menuElem.setAttribute(
            "label",
            getString("menuitem-label") || "Generate AI Summary",
          );
        },
        onCommand: () => {
          handleMenuClick();
        },
      },
    ],
  });

  ztoolkit.log("Menu registered");
}

/**
 * Handle menu click event
 */
async function handleMenuClick(): Promise<void> {
  const zoteroPane = Zotero.getActiveZoteroPane();
  const items = zoteroPane.getSelectedItems();

  if (!items || items.length === 0) {
    showAlert("No items selected");
    return;
  }

  // Filter to regular items only (not attachments or notes)
  const regularItems = items.filter((item) => item.isRegularItem());

  if (regularItems.length === 0) {
    showAlert("Please select regular items (not attachments or notes)");
    return;
  }

  // Check API key
  const apiKey = getApiKey();
  if (!apiKey) {
    showAlert("Please set your Grok API Key in Zotero AI Notes preferences");
    return;
  }

  const model = getModel();

  // Process items
  await processItems(regularItems, apiKey, model);
}

/**
 * Process multiple items
 */
async function processItems(
  items: Zotero.Item[],
  apiKey: string,
  model: string,
): Promise<void> {
  const total = items.length;
  let processed = 0;
  let succeeded = 0;
  let failed = 0;

  // Show progress window
  const progressWin = new ztoolkit.ProgressWindow(config.addonName, {
    closeOnClick: false,
  }).show();

  for (const item of items) {
    processed++;
    const title = getTitle(item);
    const shortTitle = title.length > 40 ? title.slice(0, 40) + "..." : title;
    const lineIdx = processed - 1;

    progressWin.createLine({
      text: `[${processed}/${total}] ${shortTitle}`,
      type: "default",
      progress: 0,
      idx: lineIdx,
    });

    try {
      await processItem(item, apiKey, model);
      progressWin.changeLine({
        progress: 100,
        type: "success",
        idx: lineIdx,
      });
      succeeded++;
    } catch (e) {
      const errorMsg = e instanceof Error ? e.message : "Unknown error";
      ztoolkit.log(`Error processing item ${item.id}: ${errorMsg}`);
      progressWin.changeLine({
        type: "fail",
        text: `[${processed}/${total}] ${shortTitle} - Failed`,
        idx: lineIdx,
      });
      failed++;
    }
  }

  // Show completion message
  progressWin.createLine({
    text: `Complete: ${succeeded} succeeded, ${failed} failed`,
    type: "default",
  });
  progressWin.startCloseTimer(3000);
}

/**
 * Process a single item
 */
async function processItem(
  item: Zotero.Item,
  apiKey: string,
  model: string,
): Promise<void> {
  const title = getTitle(item);
  const citationKey = getCitationKey(item);

  ztoolkit.log(`Processing: ${title}`);

  // Check for existing note
  const existingNote = await findExistingNote(item);
  if (existingNote && existingNote.sourceType === "pdf") {
    ztoolkit.log(`Skipping - already has PDF-based note`);
    return;
  }

  // Try to extract PDF text
  const pdfText = await extractPdfText(item);

  let text: string;
  let sourceType: "pdf" | "abstract";

  if (pdfText && pdfText.trim().length > 100) {
    text = pdfText;
    sourceType = "pdf";
    ztoolkit.log(`Using PDF text (${text.length} chars)`);
  } else {
    // Fallback to abstract
    const abstract = getAbstract(item);
    if (!abstract) {
      throw new Error("No PDF or abstract available");
    }
    text = abstract;
    sourceType = "abstract";
    ztoolkit.log(`Using abstract (${text.length} chars)`);
  }

  // Generate summary
  ztoolkit.log(`Calling Grok API...`);
  const summary = await generateSummary(text, apiKey, model);

  // Delete existing auto-generated notes if any
  if (existingNote) {
    await deleteAutoGeneratedNotes(item);
  }

  // Create new note
  await createSummaryNote(item, summary, title, citationKey, sourceType);

  ztoolkit.log(`Successfully processed: ${title}`);
}

/**
 * Show an alert dialog
 */
function showAlert(message: string): void {
  new ztoolkit.ProgressWindow(config.addonName)
    .createLine({
      text: message,
      type: "fail",
    })
    .show()
    .startCloseTimer(3000);
}
