/**
 * Context menu registration and handling
 */

import {
  extractPdfText,
  getAbstract,
  getTitle,
  getCitationKey,
} from "./pdfExtract";
import { generateSummary } from "./grokApi";
import {
  createSummaryNote,
  findExistingNote,
  deleteAutoGeneratedNotes,
} from "./noteCreator";
import { getApiKey, getModel } from "../utils/prefs";
import { config } from "../../package.json";

/**
 * Register the context menu item using ztoolkit
 */
export function registerMenu(): void {
  ztoolkit.Menu.register("item", {
    tag: "menuitem",
    id: `${config.addonRef}-generate-summary`,
    label: "Generate AI Summary",
    commandListener: handleMenuClick,
    icon: `chrome://${config.addonRef}/content/icons/favicon.png`,
  });

  ztoolkit.log("Menu registered");
}

/**
 * Handle menu click event
 */
async function handleMenuClick(): Promise<void> {
  const zoteroPane = Zotero.getActiveZoteroPane();
  const items = zoteroPane.getSelectedItems();

  if (!items || items.length === 0) {
    showAlert("No items selected");
    return;
  }

  // Filter to regular items only (not attachments or notes)
  const regularItems = items.filter((item) => item.isRegularItem());

  if (regularItems.length === 0) {
    showAlert("Please select regular items (not attachments or notes)");
    return;
  }

  // Check API key
  const apiKey = getApiKey();
  if (!apiKey) {
    showAlert("Please set your Grok API Key in Zotero AI Notes preferences");
    return;
  }

  const model = getModel();

  // Process items
  await processItems(regularItems, apiKey, model);
}

/**
 * Process multiple items
 */
async function processItems(
  items: Zotero.Item[],
  apiKey: string,
  model: string,
): Promise<void> {
  const total = items.length;
  let processed = 0;
  let succeeded = 0;
  let failed = 0;

  // Show progress window
  const progressWin = new ztoolkit.ProgressWindow(config.addonName, {
    closeOnClick: false,
  }).show();

  for (const item of items) {
    processed++;
    const title = getTitle(item);
    const shortTitle = title.length > 40 ? title.slice(0, 40) + "..." : title;

    const itemProgress = progressWin.createLine({
      text: `[${processed}/${total}] ${shortTitle}`,
      type: "default",
      progress: 0,
    });

    try {
      await processItem(item, apiKey, model);
      itemProgress.progress = 100;
      itemProgress.type = "success";
      succeeded++;
    } catch (e) {
      const errorMsg = e instanceof Error ? e.message : "Unknown error";
      ztoolkit.log(`Error processing item ${item.id}: ${errorMsg}`);
      itemProgress.type = "fail";
      itemProgress.text = `[${processed}/${total}] ${shortTitle} - Failed`;
      failed++;
    }
  }

  // Show completion message
  progressWin.createLine({
    text: `Complete: ${succeeded} succeeded, ${failed} failed`,
    type: "default",
  });
  progressWin.startCloseTimer(3000);
}

/**
 * Process a single item
 */
async function processItem(
  item: Zotero.Item,
  apiKey: string,
  model: string,
): Promise<void> {
  const title = getTitle(item);
  const citationKey = getCitationKey(item);

  ztoolkit.log(`Processing: ${title}`);

  // Check for existing note
  const existingNote = await findExistingNote(item);
  if (existingNote && existingNote.sourceType === "pdf") {
    ztoolkit.log(`Skipping - already has PDF-based note`);
    return;
  }

  // Try to extract PDF text
  let text: string | null = null;
  let sourceType: "pdf" | "abstract" = "abstract";

  text = await extractPdfText(item);

  if (text && text.trim().length > 100) {
    sourceType = "pdf";
    ztoolkit.log(`Using PDF text (${text.length} chars)`);
  } else {
    // Fallback to abstract
    text = getAbstract(item);
    if (!text) {
      throw new Error("No PDF or abstract available");
    }
    sourceType = "abstract";
    ztoolkit.log(`Using abstract (${text.length} chars)`);
  }

  // Generate summary
  ztoolkit.log(`Calling Grok API...`);
  const summary = await generateSummary(text, apiKey, model);

  // Delete existing auto-generated notes if any
  if (existingNote) {
    await deleteAutoGeneratedNotes(item);
  }

  // Create new note
  await createSummaryNote(item, summary, title, citationKey, sourceType);

  ztoolkit.log(`Successfully processed: ${title}`);
}

/**
 * Show an alert dialog
 */
function showAlert(message: string): void {
  new ztoolkit.ProgressWindow(config.addonName)
    .createLine({
      text: message,
      type: "fail",
    })
    .show()
    .startCloseTimer(3000);
}
