/**
 * Zotero note creation and management
 */

import { PaperSummary, formatSummaryAsHtml } from "./prompts";

/**
 * Tag used to identify auto-generated notes
 */
const AUTO_GENERATED_TAG = "auto-generated";

/**
 * Create a summary note for a Zotero item
 *
 * @param parentItem - Parent Zotero item
 * @param summary - Generated summary
 * @param title - Paper title
 * @param citationKey - Citation key
 * @param sourceType - Source type (pdf or abstract)
 * @returns Created note item
 */
export async function createSummaryNote(
  parentItem: Zotero.Item,
  summary: PaperSummary,
  title: string,
  citationKey: string,
  sourceType: "pdf" | "abstract",
): Promise<Zotero.Item> {
  // Format summary as HTML
  const htmlContent = formatSummaryAsHtml(
    summary,
    title,
    citationKey,
    sourceType,
  );

  // Create new note item
  const note = new Zotero.Item("note");
  note.libraryID = parentItem.libraryID;
  note.parentID = parentItem.id;

  // Set note content
  note.setNote(htmlContent);

  // Add tags
  note.addTag(AUTO_GENERATED_TAG);
  note.addTag(`source:${sourceType}`);

  // Save the note
  await note.saveTx();

  ztoolkit.log(`Created note ${note.id} for item ${parentItem.id}`);

  return note;
}

/**
 * Check if an item already has an auto-generated note
 *
 * @param item - Zotero item to check
 * @returns Existing note info or null
 */
export async function findExistingNote(item: Zotero.Item): Promise<{
  note: Zotero.Item;
  sourceType: "pdf" | "abstract" | "unknown";
} | null> {
  const noteIDs = item.getNotes();

  if (!noteIDs || noteIDs.length === 0) {
    return null;
  }

  for (const noteID of noteIDs) {
    const note = await Zotero.Items.getAsync(noteID);

    if (!note) continue;

    // Check if note has auto-generated tag
    const tags = note.getTags();
    const hasAutoGenTag = tags.some(
      (tag: { tag: string }) => tag.tag === AUTO_GENERATED_TAG,
    );

    if (hasAutoGenTag) {
      // Determine source type
      let sourceType: "pdf" | "abstract" | "unknown" = "unknown";

      if (tags.some((tag: { tag: string }) => tag.tag === "source:pdf")) {
        sourceType = "pdf";
      } else if (
        tags.some((tag: { tag: string }) => tag.tag === "source:abstract")
      ) {
        sourceType = "abstract";
      }

      return { note, sourceType };
    }
  }

  return null;
}

/**
 * Delete all auto-generated notes for an item
 *
 * @param item - Zotero item
 * @returns Number of deleted notes
 */
export async function deleteAutoGeneratedNotes(
  item: Zotero.Item,
): Promise<number> {
  const noteIDs = item.getNotes();

  if (!noteIDs || noteIDs.length === 0) {
    return 0;
  }

  let deletedCount = 0;

  for (const noteID of noteIDs) {
    const note = await Zotero.Items.getAsync(noteID);

    if (!note) continue;

    const tags = note.getTags();
    const hasAutoGenTag = tags.some(
      (tag: { tag: string }) => tag.tag === AUTO_GENERATED_TAG,
    );

    if (hasAutoGenTag) {
      await note.eraseTx();
      deletedCount++;
      ztoolkit.log(`Deleted auto-generated note ${noteID}`);
    }
  }

  return deletedCount;
}

/**
 * Update an existing note with new content
 *
 * @param note - Existing note item
 * @param summary - New summary
 * @param title - Paper title
 * @param citationKey - Citation key
 * @param sourceType - Source type
 */
export async function updateNote(
  note: Zotero.Item,
  summary: PaperSummary,
  title: string,
  citationKey: string,
  sourceType: "pdf" | "abstract",
): Promise<void> {
  const htmlContent = formatSummaryAsHtml(
    summary,
    title,
    citationKey,
    sourceType,
  );

  note.setNote(htmlContent);

  // Update source tag if changed
  const tags = note.getTags();
  const currentSourceTag = tags.find((tag: { tag: string }) =>
    tag.tag.startsWith("source:"),
  );

  if (currentSourceTag && currentSourceTag.tag !== `source:${sourceType}`) {
    note.removeTag(currentSourceTag.tag);
    note.addTag(`source:${sourceType}`);
  }

  await note.saveTx();

  ztoolkit.log(`Updated note ${note.id}`);
}
